# Generated by Django 5.1 on 2024-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField()),
                ('profile', models.TextField()),
            ],
            options={
                'db_table': 'test_rseumes',
                'managed': False,
            },
        ),
    ]
